---
- name: Provision instances
  hosts: localhost
  connection: local
  gather_facts: False
  
  vars:
    - ami_id: ami-b7a114d7
    - key_pair: Gia-fiona
    - instance_type: t2.micro
    - unique_count_tag: "jump-off-test"
    - environment: "development"
    - instance_tags:
         count_tag: "{{ unique_count_tag }}"
         env: "{{ environment }}"
    - group: default
    - aws_region: us-west-2

  tasks:
    - name: Include variables
      include_vars: aws-var.yml

    - name: Provision a set of instances
      ec2:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        key_name: "{{ key_pair }}"
        region: "{{ aws_region }}"
        group: "{{ group }}"
        instance_type: "{{ instance_type }}"
        instance_tags: "{{ instance_tags }}"
        image: "{{ ami_id }}"
        wait: True
        exact_count: 2
        count_tag:
          count_tag: "{{ unique_count_tag }}"
      register: ec2_information

    - name: Add instances to in-memory hosts list
      add_host: hostname={{ item.public_ip }} groupname=ec2_hosts
      with_items: "{{ ec2_information.tagged_instances }}"

    - name: Wait for instances to listen on port 22
      wait_for: state=started host={{ item.public_ip }} port=22 delay=10
      with_items: "{{ ec2_information.tagged_instances }}"

- name: Gather facts
  hosts: ec2_hosts
  gather_facts: False
  remote_user: ubuntu

  pre_tasks:
    - name: Install python
      raw: sudo apt-get install -y python-simplejson

  tasks:
    - name: Gathering ec2 facts
      ec2_facts:

- name: Configure instances
  hosts: ec2_hosts
  gather_facts: False
  remote_user: ubuntu

  vars:
    - public_key_files: ./public_keys/*.pub

  tasks:
    - name: Setup public keys
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup( 'file', item ) }}"
      with_fileglob:
        - "{{ public_key_files }}"






 


