---
- name: Provision instances
  hosts: localhost
  connection: local
  gather_facts: False
  
  vars:
    - ami_id: ami-b7a114d7
    - key_pair: Melman-fiona
    - instance_type: t2.micro
    - unique_count_tag: "jump-off-test"
    - playpen: "development"
    - instance_tags:
         count_tag: "{{ unique_count_tag }}"
         env: "{{ playpen }}"
    - group: default
    - aws_region: us-west-2
    - vpc_private:
        name: dev_vpc
        cidr_block: 10.10.10.0/24
        tags:
          env: "{{ playpen }}"
        tenancy: "default"


  tasks:
    - name: Include variables
      include_vars: aws-var.yml
      tags:
        - infrastructure

    - name: Create VPC instance for environment
      ec2_vpc_net:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ aws_region }}"
        name: "{{ vpc_private.name }}"
        cidr_block: "{{ vpc_private.cidr_block }}"
        tags: "{{ vpc_private.tags }}"
        tenancy: "{{ vpc_private.tenancy }}"
      tags:
        - infrastructure

    - name: Provision a set of instances
      ec2:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        key_name: "{{ key_pair }}"
        region: "{{ aws_region }}"
        group: "{{ group }}"
        instance_type: "{{ instance_type }}"
        instance_tags: "{{ instance_tags }}"
        image: "{{ ami_id }}"
        wait: True
        exact_count: 2
        count_tag:
          count_tag: "{{ unique_count_tag }}"
      register: ec2_information

    - name: Add instances to in-memory hosts list
      add_host: hostname={{ item.public_ip }} groupname=ec2_hosts
      with_items: "{{ ec2_information.tagged_instances }}"


- name: Gather facts
  hosts: ec2_hosts
  gather_facts: False
  remote_user: ubuntu

  pre_tasks:
    - name: Install python
      raw: sudo apt-get install -y python-simplejson

  tasks:
    - name: Gathering ec2 facts
      ec2_facts:

- name: Configure instances
  hosts: ec2_hosts
  gather_facts: False
  remote_user: ubuntu

  vars:
    - public_key_files: ./public_keys/*.pub

  tasks:
    - name: Setup public keys
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup( 'file', item ) }}"
      with_fileglob:
        - "{{ public_key_files }}"






 


