---
- hosts: localhost
  gather_facts: False

  tasks:

    - name: Include variables
      include_vars: aws-var.yml

    - name: Gather facts
      ec2_remote_facts:
         aws_access_key: "{{ ec2_access_key }}"
         aws_secret_key: "{{ ec2_secret_key }}"
         region: us-west-2
      register: ec2

    - name: Echo EC2 facts
      debug:
        msg: "EC2: {{ ec2 }}"

    - name: Echo EC2 variables
      debug:
        msg: "ansible_ec2_instance_id: {{ ansible_ec2_instance_id }}"


