---
- hosts: localhost
  gather_facts: True

  tasks:

    - name: Include variables
      include_vars: aws-var.yml

    - name: Gather facts
      ec2_remote_facts:
         aws_access_key: "{{ ec2_access_key }}"
         aws_secret_key: "{{ ec2_secret_key }}"
         region: us-west-2
      register: ec2

